### PR TITLE
Pkerpedjiev/nested checkboxes

### LINKED ISSUE #384: Add nesting to the tileset list
The current tileset list is overwhelming:

image

There lots of datasets listed without any grouping. We need a way to partition them into groups so that the list can be cleaned up.

## Steps to reproduce

1. Go to higlass.io/app
2. Add dataset -> center
3. See tileset list

One option is to use [react-checkbox-tree](https://github.com/jakezatecky/react-checkbox-tree).

### PR DESCRIPTION
**Pull request by pkerpedjiev**
## Description

This change introduces nested checkboxes to the tileset finder (Add Track) dialog. This makes it possible to assign a group to each tileset and to group them by their groups. 

image

This should clean up the list of tilesets making it easier for users to find what they want.

Fixes #384
Goes with (requires): https://github.com/higlass/higlass-server/pull/78

## Checklist

- [x] Unit tests added or updated
- [x] Documentation added or updated
- [NA] Example added or updated
- [x] Screenshot for visual changes (e.g. new tracks)

### CODE REVIEW

**Comment by pkerpedjiev** [comment]
Waiting on https://github.com/higlass/higlass/pull/427 so that I can update the docs.

File: app/scripts/AddTrackModal.js [hunk 1]
```diff
@@ -148,23 +156,25 @@ class AddTrackModal extends React.Component {
...
           { form }
           {
-            this.props.hidePlotTypeChooser ? null :
-            <PlotTypeChooser
-              ref={(c) => { this.plotTypeChooser = c; }}
-              datatypes={this.state.selectedTilesets.map(x => x.datatype)}
-              onPlotTypeSelected={this.handlePlotTypeSelected.bind(this)}
-              orientation={orientation}
-            />
+            this.props.hidePlotTypeChooser ? null
```
Comment (flekschas) [inline app/scripts/AddTrackModal.js]: Not critical but this can be shortened to

```javasacript
!this.props.hidePlotTypeChooser && (...)
```

File: app/scripts/PlotTypeChooser.js [hunk 2]
```diff
@@ -91,7 +91,13 @@ class PlotTypeChooser extends React.Component {
     }
 
     return (<div>
-      { AVAILABLE_TRACK_TYPESList }
+      { AVAILABLE_TRACK_TYPESList.length ?
```
Comment (flekschas) [inline app/scripts/PlotTypeChooser.js]: Same as above instead of `?` one can use `&&` to not having to deal with `: null`. Again this is not important, just FYI

File: app/scripts/TilesetFinder.js [hunk 3]
```diff
@@ -188,7 +176,7 @@ class TilesetFinder extends React.Component {
   }
 
   handleSelect() {
-    const { selectedOptions } = ReactDOM.findDOMNode(this.multiSelect);
+    const { selectedOptions } = this.multiSelect;
```
Comment (flekschas) [inline app/scripts/TilesetFinder.js]: Just double checking: `ReactDOM.findDOMNode` is no longer needed?

File: app/scripts/TilesetFinder.js [hunk 4]
```diff
@@ -200,70 +188,142 @@ class TilesetFinder extends React.Component {
...
   }
 
+  /*
+   * Create the nested checkbox tree by partitioning the
+   * list of available datasets according to their group
+   *
+   * @param {dict} datasetsDict A dictionary of id -> tileset
+   *  def mappings
+   * @param {string} filter A string to filter the results by
+   * @returns {list} A list of items that define the nested checkbox
```
Comment (flekschas) [inline app/scripts/TilesetFinder.js]: I'd use proper JS dtypes: `dict` => `object` and `list` => `array`

File: app/scripts/TilesetFinder.js [hunk 5]
```diff
@@ -200,70 +188,142 @@ class TilesetFinder extends React.Component {
...
+   *  structure
+   *  {
+   *    'name': 'blah',
+   *    'value': 'blah',
+   *    'children': 'blah',
```
Comment (flekschas) [inline app/scripts/TilesetFinder.js]: Looking at line `216` it seems that children is suppose to be an `array` and not a string? Is that right or am I misunderstanding something?

File: app/styles/TilesetFinder.css [hunk 6]
```diff
@@ -0,0 +1,249 @@
+@font-face {
+  font-family: 'FontAwesome';
+  src: url('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/fonts/fontawesome-webfont.eot?v=4.7.0');
```
Comment (flekschas) [inline app/styles/TilesetFinder.css]: What do we need fontawesome for? Could we just download and inline the icon? External references can lead to issues when being offline or within some secret organizations intranet.

File: karma.conf.js [hunk 7]
```diff
@@ -13,8 +13,10 @@ module.exports = (config) => {
       'node_modules/pixi.js/dist/pixi.js',
       'node_modules/react-bootstrap/dist/react-bootstrap.js',
       'node_modules/bootstrap/dist/css/bootstrap.min.css',
+      'node_modules/font-awesome/css/font-awesome.css',
```
Comment (flekschas) [inline karma.conf.js]: If possible I would be great if we can avoid adding another big dependency :)

File: package.json [hunk 8]
```diff
@@ -113,6 +114,7 @@
     "eslint-plugin-react": "^7.11.1",
     "fast-css-loader": "^1.0.2",
     "fast-sass-loader": "^1.4.6",
+    "font-awesome": "^4.7.0",
```
Comment (flekschas) [inline package.json]: As above. Just pinning

File: webpack.config.js [hunk 9]
```diff
@@ -32,6 +32,7 @@ module.exports = (env, argv) => ({
       path.resolve(__dirname, 'app'),
       path.resolve(__dirname, 'docs', 'examples'),
       path.resolve(__dirname, 'node_modules'),
+      path.resolve(__dirname, 'lib', 'vendor')
```
Comment (flekschas) [inline webpack.config.js]: What's this used for?

File: app/scripts/AddTrackModal.js (hunk 1 above)
Comment (pkerpedjiev) [reply app/scripts/AddTrackModal.js]: Not in this case. Notice that it's `a ? null : b`, which isn't the same as `a && b`.

File: app/scripts/PlotTypeChooser.js (hunk 2 above)
Comment (pkerpedjiev) [reply app/scripts/PlotTypeChooser.js]: Here it works.

File: app/scripts/TilesetFinder.js (hunk 4 above)
Comment (pkerpedjiev) [reply app/scripts/TilesetFinder.js]: Sure.

File: app/scripts/TilesetFinder.js (hunk 3 above)
Comment (pkerpedjiev) [reply app/scripts/TilesetFinder.js]: Nope.

File: app/scripts/TilesetFinder.js (hunk 5 above)
Comment (pkerpedjiev) [reply app/scripts/TilesetFinder.js]: No, my docstring was just wrong. Good catch.

File: app/styles/TilesetFinder.css (hunk 6 above)
Comment (pkerpedjiev) [reply app/styles/TilesetFinder.css]: If some secret organizations' internet isn't connected they're going to have bigger fish to fry than the icons here.

But nevertheless, I included them as inlined SVGs.

File: karma.conf.js (hunk 7 above)
Comment (pkerpedjiev) [reply karma.conf.js]: Ok, it's gone.

File: package.json (hunk 8 above)
Comment (pkerpedjiev) [reply package.json]: Gone.

File: webpack.config.js (hunk 9 above)
Comment (pkerpedjiev) [reply webpack.config.js]: I just added it to put local libraries so that I could work on HiGlass while on the plane :)

**Comment by flekschas** [comment]
Awesome! Thanks!

The PR TravisCI check fails but it seems like it's an issue on Travis side
