### PR TITLE
Fix passive events intervention

### LINKED ISSUE #596: newest chrome scroll context
_Commit_: 

#### Steps to reproduce
1. Update to newest chrome (73.0.3683.86)
2. Go to higlass.io.
3. "scroll down" with mouse on the topmost higlass display, with the intention that it should zoom out.

#### Observed behavior
- the page is scrolled down. with a glitchy mix of zoom-out.

#### Expected behavior
- the page should stay put and the display should zoom out.

### PR DESCRIPTION
**Pull request by pkerpedjiev**
## Description

What was changed in this pull request?

Make event handlers non-passive.

Why is it necessary?

Because scrolling was broken with the latest version of chrome.

Fixes #596

## Checklist

- [o] Unit tests added or updated
- [o] Documentation added or updated
- [o] Example added or updated
- [o] Screenshot for visual changes (e.g. new tracks)
- [x] Updated CHANGELOG.md

### CODE REVIEW

File: app/scripts/services/dom-event.js [hunk 1]
```diff
@@ -59,7 +59,11 @@ const register = pubSub => (event, newElement, useCapture = false) => {
   registeredEls[event] = newElement;
   registeredEls[event].__handler__ = getEventHandler(event, pubSub);
   registeredEls[event].addEventListener(
-    event, registeredEls[event].__handler__, useCapture
+    event, registeredEls[event].__handler__,
+    {
+      capture: useCapture,
+      passive: false,
```
Comment (flekschas) [inline app/scripts/services/dom-event.js]: Just out of curiosity, is this turning all captured events into active events? I haven't used that feature before that's why I am asking :)

Comment (pkerpedjiev) [reply app/scripts/services/dom-event.js]: Yes, that was the default until Google changed it for `wheel` and `mousewheel` events in Chrome 73.
